### ISSUE TITLE
Reporting a CID

### ISSUE THREAD

**Issue by rjubran** [nftstorage/nftstorage.link#149]
Unfortunately could not find the badbits denylist request page, so putting this here. My org received a phishing attack from the following CID:

bafybeifh3smysh2mf37vaohwc2gpcydxdouxzlemuujbvwwi4eplnurfua

**Comment by dchoi27** [comment]
Thanks for reporting! @vasco-santos can you block?

**Comment by vasco-santos** [comment]
Thanks, this is now in our deny list
