### ISSUE TITLE
Sanitize ipfs links?

### ISSUE THREAD

**Issue by melMass** [nftstorage/nftstorage.link#177]
Hi,

### Issue

When generative tokens (html CAR packages) are viewed from the gateway. Direct links to ipfs (i.e `ipfs://<CID>`) are not sanitized:

DOES NOT WORK -> https://bafybeifsiea24k46cgebr6pcleqmqe6kyqzh4pw4rexep4xdr337625oyi.ipfs.nftstorage.link/
WORKS -> https://ipfs.io/ipfs/bafybeifsiea24k46cgebr6pcleqmqe6kyqzh4pw4rexep4xdr337625oyi/

Though looking at the source code I'm not such of the artist's logic there.

**Comment by melMass** [comment]
So it seems like the reason the token actually ends up working is by providing a fallback to "popular" gateways, hence given the current CSP policy it's failing on NFT.storage. 
I'm not sure how feasable or if there is any standard on that end, but resolving `ipfs://` requests to the gateway makes sense IMO

**Comment by dchoi27** [comment]
Oh, interesting thought. @Gozala does this fit with how you're thinking about the ideal state of how browsers / gateways handle external content?
