### ISSUE TITLE
Cloudflare verification causes issues for metadata and image display

### ISSUE THREAD

**Issue by nukec** [nftstorage/nftstorage.link#219]
There is a massive problem accessing metadata or images on nftstorage.link ipfs because it is behind cloudflare. I cannot process why would those two be behind cloudflare verification system, which prevents images or metadata loading on any websites that display those via onchain data.

For example solana defi/dex are unable to access any images that are hosted on nftstorage.link, examples of top defi products on solana:
- raydium.io
- step.finance
- meteora.ag
- jup.ag
- orca.so

Examples:
![image](https://github.com/nftstorage/nftstorage.link/assets/3589518/64097cb1-cfab-4705-8861-ee5396109b12)
![image](https://github.com/nftstorage/nftstorage.link/assets/3589518/dbc89268-0815-40ef-80dc-2bea87e7043c)

The whole cloudflare verification for metadata and images on nftstorage.link should be disabled, and just implement some rate limit if you want to prevent abuse. I also suggest to use https://fotofolio.xyz/ or similar caching service that is inbetween layer that will cache image, if you want to prevent constant fetching from your servers. Aka you would overwrite response if you access for instance https://bafybeihn5s2ykzqwpmb6d4dbowecovc7vo2wjx7zjltur7sl4ykfhbmoaq.ipfs.nftstorage.link/ it overwrites request to https://img.fotofolio.xyz/?url=https%3A%2F%2Fbafybeihn5s2ykzqwpmb6d4dbowecovc7vo2wjx7zjltur7sl4ykfhbmoaq.ipfs.nftstorage.link

Another people have same issues, and discord is full of this problems but no response yet:
https://www.reddit.com/r/solana/comments/1ck17cp/nftstoragelink_why_protect_tokens_metadata_json/

**Comment by elizabeth-griffiths** [comment]
Thank you for highlighting this to us. No one else has shared this reddit link yet, so we appreciate it. 
 meteora.ag was caught in the filter, NFT.Storage data should start loading there now.

Can you please confirm if the following are still having issues: 
raydium.io
step.finance
jup.ag
orca.so

**Comment by nukec** [comment]
@elizabeth-griffiths meteora.ag now works. others are still not displaying:
- raydium.io,
- step.finance#
- orca.so and
- explorer.solana.com you can check here: https://explorer.solana.com/address/45EgCwcPXYagBC7KqBin4nCFgEZWN7f3Y6nACwxqMCWX

meteora.ag works now that you put filter, but do we have to do this filter for each domain of new decentralized app in the future? any reason why imagery is behind cloudflare?

thanks a lot for your work.

**Comment by jovjou** [comment]
Hi, @elizabeth-griffiths,

Could you please help us with the issues concerning the ipfs.nftstorage.link gateway? It appears that the entire gateway is blocked for visitors from Ukraine (and possibly other countries as well). Everyone is encountering the following error when trying to access any IPFS URL through the gateway:
```
Sorry, you have been blocked
You are unable to access nftstorage.link
```

The Cloudflare Ray ID is: 8b29449c3d4624bd

It is crucial for many services that rely on your service to have access to this gateway and all associated links. Please let me know if there is anything we can do from our side. Thanks.

**Comment by nukec** [comment]
they don't seem to care. take months to reply and fix simple stuff, which shouldn't be implemented like they have it at the first place.

**Comment by elizabeth-griffiths** [comment]
These should all be resolved. Please open a new ticket if they are not.
