### ISSUE TITLE
Add IPNS resolution to race+cache

### ISSUE THREAD

**Issue by vasco-santos** [nftstorage/nftstorage.link#27]
Follow up on https://github.com/nftstorage/nftstorage.link/pull/25 by adding IPNS resolution to gateway race + cache, as well as collect its own metrics

**Comment by lidel** [comment]
There are some relevant notes / wip work  in https://github.com/ipfs/go-ipfs/issues/8717.
For `/ipns/` specifically, we should leverage TTL from DNSLink / IPNS Record as noted in https://github.com/ipfs/go-ipfs/issues/1818#issuecomment-1015849462.
